In [1]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import scipy.io.wavfile as sci_wav  # Open wav files
import os  

ROOT_DIR = 'C:/data/cats_dog/all/'
X_path = os.listdir(ROOT_DIR)
X_path

['cat_1.wav',
 'cat_10.wav',
 'cat_100.wav',
 'cat_101.wav',
 'cat_102.wav',
 'cat_103.wav',
 'cat_105.wav',
 'cat_106.wav',
 'cat_107.wav',
 'cat_108.wav',
 'cat_109.wav',
 'cat_11.wav',
 'cat_110.wav',
 'cat_112.wav',
 'cat_113.wav',
 'cat_114.wav',
 'cat_115.wav',
 'cat_116.wav',
 'cat_117.wav',
 'cat_118.wav',
 'cat_119.wav',
 'cat_12.wav',
 'cat_120.wav',
 'cat_121.wav',
 'cat_122.wav',
 'cat_123.wav',
 'cat_124.wav',
 'cat_125.wav',
 'cat_126.wav',
 'cat_127.wav',
 'cat_128.wav',
 'cat_129.wav',
 'cat_13.wav',
 'cat_130.wav',
 'cat_131.wav',
 'cat_132.wav',
 'cat_133.wav',
 'cat_134.wav',
 'cat_135.wav',
 'cat_136.wav',
 'cat_137.wav',
 'cat_138.wav',
 'cat_139.wav',
 'cat_14.wav',
 'cat_140.wav',
 'cat_141.wav',
 'cat_142.wav',
 'cat_143.wav',
 'cat_144.wav',
 'cat_146.wav',
 'cat_147.wav',
 'cat_148.wav',
 'cat_149.wav',
 'cat_15.wav',
 'cat_150.wav',
 'cat_151.wav',
 'cat_152.wav',
 'cat_153.wav',
 'cat_154.wav',
 'cat_155.wav',
 'cat_156.wav',
 'cat_157.wav',
 'cat_158.wav',


In [2]:
y = [0 if 'cat' in f else 1 for f in X_path]
y

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [3]:
#train_test_split(전체파일명list, 0/1분류list, 검증비율)
X_train, X_test, y_train, y_test = train_test_split(X_path, y, test_size=0.33)

print("in X, there is {} cats and {} dogs".format(len(y) - sum(y), sum(y)))
print("in X_train, there is {} cats and {} dogs".format(len(y_train) - sum(y_train), sum(y_train)))
print("in X_test, there is {} cats and {} dogs".format(len(y_test) - sum(y_test), sum(y_test)))

in X, there is 164 cats and 113 dogs
in X_train, there is 111 cats and 74 dogs
in X_test, there is 53 cats and 39 dogs


In [5]:
def read_wav_files(wav_files):
    if not isinstance(wav_files, list):
        wav_files = [wav_files]
    return [sci_wav.read(ROOT_DIR + f)[1] for f in wav_files]

print(read_wav_files('cat_1.wav'))
print(read_wav_files(['cat_1.wav', 'cat_2.wav']))

[array([ 124,  107,    7, ..., -545, -494, -529], dtype=int16)]
[array([ 124,  107,    7, ..., -545, -494, -529], dtype=int16), array([-1028, -1039, -1064, ...,     6,    38,     2], dtype=int16)]


In [6]:
X_train, X_test = map(read_wav_files, [X_train, X_test])
X_train

[array([   8,    6,    2, ..., -195, -174, -140], dtype=int16),
 array([  0,  -1,   0, ..., 569, 430, 254], dtype=int16),
 array([  0,   0,   0, ..., -41, -14, -10], dtype=int16),
 array([  0,   1,   8, ..., 143, 171, 151], dtype=int16),
 array([843, 911, 970, ..., 435, 334, 589], dtype=int16),
 array([ 1824,  3000,  3286, ..., -4870, -4889, -5298], dtype=int16),
 array([  -1,    0,   -1, ..., -246, -225, -210], dtype=int16),
 array([ 0,  0,  0, ...,  0, -2,  1], dtype=int16),
 array([-198,    3,   87, ...,  -52,  -80,  -57], dtype=int16),
 array([  -1,    0,   -1, ..., -106, -145, -174], dtype=int16),
 array([ -68,  -68,  -54, ..., -972, -990, -334], dtype=int16),
 array([  0,   0,   0, ..., -81,  83, 200], dtype=int16),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int16),
 array([-1,  0, -1, ..., 22, 22, 22], dtype=int16),
 array([   0,    0,    0, ...,  125, -942, -431], dtype=int16),
 array([ 93,  22,  48, ..., 116,  63, -40], dtype=int16),
 array([-1,  0, -3, ..., 88, 80, 76], dtype=int1